sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sathishpskdocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sathishpskdocker/react-test npm test

after_success:
  - docker build -t sathishpskdocker/multi-client ./client
  - docker build -t sathishpskdocker/multi-nginx ./nginx
  - docker build -t sathishpskdocker/multi-server ./server
  - docker build -t sathishpskdocker/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push sathishpskdocker/multi-client
  - docker push sathishpskdocker/multi-nginx
  - docker push sathishpskdocker/multi-server
  - docker push sathishpskdocker/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucker_name: elasticbeanstalk-us-west-2-194531873493
  bucker_path: docker-multi
  On:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  